services:
  nacos:
    container_name: nacos_server
    image: 'nacos/nacos-server:latest'
    environment:
      - 'MODE=standalone'
    ports:
      - '8848:8848'
      - '9848:9848'
  postgres:
    container_name: blog_postgres_db
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=blog'
      - 'POSTGRES_PASSWORD=secret_password'
      - 'POSTGRES_USER=blog'
    ports:
      - '5432:5432'